runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

skip_files:
- ui/

handlers:
- url: /api/.*
  script: main.app

- url: /(.*\.(js|css|png|map))$
  static_files: dist/\1
  upload: dist/.*\.(js|css|png|map)$

# Catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
